//import { h } from 'vue'
import { createRouter, createWebHistory } from 'vue-router/auto'
import { routes } from 'vue-router/auto-routes'

const router = createRouter({
  history: createWebHistory(import.meta.env.BASE_URL),
  routes

  /* Notes:
     - routes array is no longer needed in VueRouter from unplugin component (the routes array is generated by the plugin)
     - /views folder is renamed to /pages - since its what unplugin is using (see https://uvr.esm.is/introduction )


  routes: [
    {
      path: '/',
      name: 'home',
      component: () => import('@/views/HomeView.vue')
    },
    {
      path: '/projects',
      name: 'projects',
      component: () => import('@/views/ProjectsView.vue')
    },
    {
      path: '/projects/:id',
      name: 'single-project',
      component: () => import('@/views/SingleProjectView.vue')
    },
    {
      path: '/:catchAll(.*)*',
      name: 'not-found',
      component: h('h5', { style: 'color: red' }, '404 Not Found')
    }
  ]
  */
})

export default router
